sudo: required

services:
 - docker

script:
 - export TAG=`if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master" ]]; then echo "latest"; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi`
 - export REPO=sthuber90/revpi
 - cd revpi-docker && 
   chmod +x repo/usr/bin/piSerial &&
   chmod +x repo/usr/bin/revpi-config &&
   chmod +x repo/opt/vc/bin/vcgencmd &&
   docker build -t $REPO:$TAG -f Dockerfile .

after_success:
 - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
 - if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master" ]]; then
   docker tag $REPO:$TAG $REPO:$TRAVIS_BUILD_NUMBER;
   docker push $REPO:$TRAVIS_BUILD_NUMBER;
   fi   
 - docker push $REPO:$TAG